### ISSUE TITLE
Add common algos in Basics folder

### ISSUE THREAD

**Issue by thepurpleowl** [thepurpleowl/House-of-Codes#8] opened 2020-10-06 05:00 UTC
- **You can add standard algorithms in appropriate sub-directories.**
For example if you want to add a code for binary tree and the binary tree sub-directory is **not present already**, make one and add your codes there.

- **Create a new issue for specific algorithms**
For example if you want to add a code for binary tree and the binary tree sub-directory is not present already, make another issue, assign that to yourself and contribute.

- **Codes need not to be limited to any specific language.**

- **Only algorithm implementations will be accepted, including pseudo code or theoretical resources are not the objective of this repo.**

**Comment by susmita2000** [comment] 2020-10-06 07:54
Can I add sorting algorithms in c++?

**Comment by thepurpleowl** [comment] 2020-10-06 08:00
@susmita2000 go ahead. Make a 'Sorting' subdirectory

**Comment by manvendrajpoot** [comment] 2020-10-06 09:04
I want to add the following sub-directories -
i) Dynamic Programming questions
ii) Backtracking and Binary Search Application based questions.
iii)Trie and XOR problems.
iii)Segment-tree

**Comment by manvendrajpoot** [comment] 2020-10-06 09:08
And one more thing I would like to do this in C++.

**Comment by thepurpleowl** [comment] 2020-10-06 10:52
@manvendra264 Yeah go ahead. Make sub-directories in Basics/ for each one of them and update the README.

**Comment by hryxna** [comment] 2020-10-06 13:19
Is it ok @thepurpleowl if create a new director for Data structures? and add all the codes of data structures in them?

**Comment by thepurpleowl** [comment] 2020-10-06 13:31
> Is it ok @thepurpleowl if create a new director for Data structures? and add all the codes of data structures in them? 

Yeah sure. Make one subdirectory for one data structure inside Basics/DataStructures. 

And update README.

**Comment by SidBthegr8** [comment] 2020-10-07 13:37
I wanna get started with adding common graph algorithms. Is that fine?

**Comment by SidBthegr8** [comment] 2020-10-07 13:39
and I propose to do this in cpp.

**Comment by Md-Atik-Enam** [comment] 2021-03-23 16:09
Added basic string algorithms in java that involve hashing, kmp, suffix array

**Comment by Shrutika-TechSavvy** [comment] 2024-10-03 18:42
Hi @thepurpleowl 

I would like to contribute to this issue by adding algorithms related to Singly Linked Lists. I can provide implementations for various linked list operations such as:

Insertion
Deletion
Searching
Reversing a linked list
Detecting cycles (using Floyd’s cycle-finding algorithm).

**Comment by Shrutika-TechSavvy** [comment] 2024-10-08 03:31
*Hey ,*

I hope this email finds you well. I wanted to reach out regarding *Issue #8*
in the *House-of-Codes* repository. I recently submitted and merged a pull
request (#1) addressing the linked list algorithms as mentioned in the
issue.
[image: image.png]
 Additionally, I noticed that the repository appears as *"Not
Participating"* in Hacktoberfest on my profile.

However, I noticed that the issue is still open and assigned to me. I
wanted to confirm if there is any additional work required, or if it would
be possible to close the issue now that the pull request has been merged.

Please let me know if there are any further steps I need to take or any
improvements you'd like me to make.

Thank you for your time, and I look forward to your response.

Best regards,
Shrutika Pawar
GitHub: [Shrutika-TechSavvy]

**Comment by Shrutika-TechSavvy** [comment] 2024-10-08 03:34
I hope this email finds you well. I wanted to reach out regarding *Issue #8* in
the *House-of-Codes* repository. I recently submitted and merged a pull
request (#1) addressing the linked list algorithms as mentioned in the
issue.

[image: image.png]
Additionally, I noticed that the repository appears as *"Not Participating"* in
Hacktoberfest on my profile.


However, I noticed that the issue is still open and assigned to me. I
wanted to confirm if there is any additional work required, or if it would
be possible to close the issue now that the pull request has been merged.

Please let me know if there are any further steps I need to take or any
improvements you'd like me to make.

Thank you for your time, and I look forward to your response.

Best regards,
Shrutika Pawar
GitHub: [Shrutika-TechSavvy]

**Comment by thepurpleowl** [comment] 2024-10-11 06:04
@Shrutika-TechSavvy your PR https://github.com/thepurpleowl/House-of-Codes/pull/69 doesn't contain any implementation. PR has only ".txt" files with algorithms described. This repo only accepts implementations.

**Comment by thepurpleowl** [comment] 2024-10-11 06:07
Updated the description of the issue for future contributors.

**Comment by Shrutika-TechSavvy** [comment] 2024-10-11 12:39
> @Shrutika-TechSavvy your PR #69 doesn't contain any implementation. PR has only ".txt" files with algorithms described. This repo only accepts implementations.
@thepurpleowl ,
So, I can add the implementation using java. Will it be okay to again continue with this?

**Comment by thepurpleowl** [comment] 2024-10-11 14:48
@Shrutika-TechSavvy Sure. Please take a note of [Contributing guidelines](https://github.com/thepurpleowl/House-of-Codes/blob/master/CONTRIBUTING.md).

**Closed as not planned** 2024-10-11 15:02 UTC
Labels: hacktoberfest, collective_issue
